module.exports = {
    BILLING_CYCLES_FETCHED:'BILLING_CYCLES_FETCHED',
    BILLING_SUMMARY_FATCHED:'BILLING_SUMMARY_FATCHED',
    TAB_SELECTED:'TAB_SELECTED',
    TABS_SHOWED:'TABS_SHOWED',
    billingCycleForm:'billingCycleForm'
}