# Generated by Django 2.2.5 on 2019-09-20 15:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('orig_dest', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.IntegerField(choices=[(0, 'PENDENTE'), (1, 'OK'), (2, 'CANCELADO')], default='PENDENTE')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('unit', models.CharField(default='UNIDADE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='operations.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('labor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('off', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.IntegerField(choices=[(0, 'PENDENTE'), (1, 'OK'), (2, 'CANCELADO')], default='PENDENTE')),
                ('date', models.DateField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.Client')),
                ('itens', models.ManyToManyField(related_name='itemService', to='operations.Stock')),
                ('material', models.ManyToManyField(related_name='materialService', to='operations.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(0, 'VENDA'), (1, 'COMPRA')])),
                ('status', models.IntegerField(choices=[(0, 'PENDENTE'), (1, 'OK'), (2, 'CANCELADO')], default='PENDENTE')),
                ('date', models.DateField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('opid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.SalesOrBuy')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.Product')),
            ],
        ),
    ]
