# Generated by Django 2.2.5 on 2019-09-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_salesorbuy_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.Service')),
            ],
        ),
    ]
