# Generated by Django 2.2.5 on 2019-09-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.Client'),
        ),
    ]
