# Generated by Django 2.2.5 on 2019-09-25 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20190925_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_item', models.IntegerField(choices=[(0, 'ITEM'), (1, 'MATERIAL')])),
                ('qtd', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('opid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Service')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
