# Generated by Django 2.2.5 on 2019-09-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20190925_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='opid',
            new_name='sbid',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='op_type',
            field=models.IntegerField(choices=[(0, 'COMPRA'), (1, 'VENDA'), (2, 'ITEM'), (3, 'MATERIAL')], default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='svid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Service'),
        ),
        migrations.DeleteModel(
            name='CartServiceItem',
        ),
    ]
