# Generated by Django 2.2.5 on 2019-09-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20190926_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorbuy',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='op_type',
            field=models.IntegerField(choices=[(0, 'COMPVEND'), (1, 'ITEM'), (2, 'MATERIAL')], default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sbid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.SalesOrBuy'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='svid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Service'),
        ),
    ]
