# Generated by Django 2.2.5 on 2019-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_service_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='off',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
