# Generated by Django 2.2.5 on 2019-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20190928_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='off',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, null=True),
        ),
    ]
