# Generated by Django 2.2.5 on 2019-10-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_auto_20191007_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipliers', models.TextField(blank=True, default='{}', null=True)),
            ],
        ),
    ]
