# Generated by Django 2.2.5 on 2019-11-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_auto_20191109_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='variables',
        ),
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='float', max_length=30),
        ),
        migrations.AddField(
            model_name='config',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='value_type',
            field=models.CharField(default='float', max_length=10),
        ),
    ]
