# Generated by Django 2.2.5 on 2019-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_auto_20191110_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(default='multplier', max_length=30),
        ),
        migrations.AlterField(
            model_name='config',
            name='value_type',
            field=models.CharField(default='float', max_length=20),
        ),
    ]
